modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/Transprotwo/issues"
license="GNU Lesser General Public License v3.0"

[[mods]]
modId="transprotwo"
version="${file.jarVersion}"
displayName="Transprot"
displayURL="https://www.curseforge.com/minecraft/mc-mods/transprotwo"
authors="Mrbysco, MrRiegel"
description='''
Transport over short distance without cables.
'''
[[dependencies.transprotwo]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.transprotwo]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.70-beta,)"
ordering="NONE"
side="BOTH"