modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Mrbysco/Transprotwo/issues"
license="GNU Lesser General Public License v3.0"

[[mods]]
modId="transprotwo"
version="${file.jarVersion}"
displayName="Transprot"
displayURL="https://www.curseforge.com/minecraft/mc-mods/transprotwo"
authors="Mrbysco, MrRiegel"
description='''
Item transport over short distance without cables.
'''
[[dependencies.transprotwo]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"