modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Mrbysco/Transprotwo/issues"
license="GNU Lesser General Public License v3.0"

[[mods]]
modId="transprotwo"
version="${file.jarVersion}"
displayName="Transprot"
displayURL="https://www.curseforge.com/minecraft/mc-mods/transprotwo"
authors="Mrbysco, MrRiegel"
description='''
Transport over short distance without cables.
'''
[[dependencies.transprotwo]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.transprotwo]]
modId="forge"
mandatory=true
versionRange="[47.1.3,)"
ordering="NONE"
side="BOTH"