modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Mrbysco/Transprotwo/issues"
license="GNU Lesser General Public License v3.0"

[[mods]]
modId="transprotwo"
version="${file.jarVersion}"
displayName="Transprot"
displayURL="https://www.curseforge.com/minecraft/mc-mods/transprotwo"
authors="Mrbysco, MrRiegel"
description='''
Transport over short distance without cables.
'''
[[dependencies.transprotwo]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.transprotwo]]
modId="forge"
mandatory=true
versionRange="[41.0.94,)"
ordering="NONE"
side="BOTH"